server:
  port: 8002

dubbo:
  application:
    # 应用名称
    name: my-consumer
  registry:
    # 注册中心地址 （multicast://224.5.6.7:1234）
    address: zookeeper://192.168.17.223:2181?backup=192.168.17.223:2182,192.168.17.223:2183
    # 超时时间
    timeout: 6000
  metadata-report:
    #元数据 （减少服务提供者和消费者之间不必要的数据传输）
    address: zookeeper://192.168.17.223:2181?backup=192.168.17.223:2182,192.168.17.223:2183
  protocol:
    # 协议名称
    name: dubbo
    # 协议端口号
    port: 20880
  scan:
    # 扫描包的位置 （暴露的服务）
    base-packages: cn.liang.provider.service